SelfTestIP: 223.5.5.5
CloudFlare:
  mail: xxx@gmail.com
  token: xxx
SMTP:
  #SMTP服务器
  host: smtp.qq.com
  #密码
  pass: xxxxx
  #接受者
  receivers: xxxxx@qq.com
  #用户
  user: xxxxx@qq.com
#将要监控的域名记录
domains:
  domain:
    name: xxx.com
    zone:
      'xxx0.m': 'http://tj.baidu.com:31800'
      'xxx1.xian': 'http://tj.baidu.com:23193'
      'xxx2.xian': 'http://tj.baidu.com:23202'
    #备用记录 都写在这里
    records:
    - content: 113.2.2.2
      name: 'xxx0.com'
      type: A
      proxied: false
    - content: 113.2.2.3
      name: 'xxx1.com'
      type: A
      proxied: false
    - content: 113.2.2.2
      name: 'xxx2.com'
      type: A
      proxied: false